//
// Created by ebalo on 11/08/22.
//

#ifndef ABYSS_VERSION_H
#define ABYSS_VERSION_H

#pragma once

#define ABYSS_LOGGER_VER_MAJOR 1
#define ABYSS_LOGGER_VER_MINOR 2
#define ABYSS_LOGGER_VER_PATCH 1

#define ABYSS_LOGGER_VERSION (ABYSS_LOGGER_VER_MAJOR * 10000 + ABYSS_LOGGER_VER_MINOR * 100 + ABYSS_LOGGER_VER_PATCH)

#endif //ABYSS_VERSION_H
