//
// Created by ebalo on 11/08/22.
//

#ifndef ABYSS_VERSION_H
#define ABYSS_VERSION_H

#pragma once

#define ABYSS_CRYPTO_VER_MAJOR 0
#define ABYSS_CRYPTO_VER_MINOR 1
#define ABYSS_CRYPTO_VER_PATCH 0

#define ABYSS_CRYPTO_VERSION (ABYSS_CRYPTO_VER_MAJOR * 10000 + ABYSS_CRYPTO_VER_MINOR * 100 + ABYSS_CRYPTO_VER_PATCH)

#endif //ABYSS_VERSION_H
